#!/usr/bin/env Rscript

# where are we running this from
scriptdir <-
   gsub('--file=','',
        grep(pattern='--file=', value=T,
             commandArgs(trailingOnly = FALSE))[1])
scriptdir <- normalizePath(dirname(scriptdir))

# grab shiny with pacman
if (! "pacman" %in% installed.packages())
  install.packages("pacman")
pacman::p_load(shiny)


# sum(map {ord} split(//, 'shiny')) => 555
runApp(scriptdir, host='0.0.0.0', port=1555)
