#!/usr/bin/env Rscript
scriptdir <- gsub('--file=','', grep(pattern='--file=', value=T, commandArgs(trailingOnly = FALSE))[1])
shiny::runApp(normalizePath(dirname(scriptdir)), host='0.0.0.0', port=9876)

